### ISSUE TITLE
kenuosec

### ISSUE THREAD

**Issue by lkgGitHub** [Camsyn/OOAD-SUSTECH-STORE#1]
您好，请求下您是 https://github.com/kenuosec 这个组织下的吗？这个组织fork了我的项目，想要联系下您

**Comment by Camsyn** [comment]
您好, 我不是该组织下的。这个项目也是我们的学校课程项目。

**Comment by lkgGitHub** [comment]
多谢，打扰了~

**Comment by Camsyn** [comment]
这个好像也是他fork了我的项目。他fork完我就改成了private了（毕竟是课程项目初期）。我并无他的联系方式。

**Comment by lkgGitHub** [comment]
好的，感谢
